name: Matrix demo
on:
  push:
    branches:
      - master
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12, 14]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          - node-version: 18
          - operating-system: ubuntu-latest
    runs-on: ${{matrix.operating-system}}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build

